// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.boboyuwu.xnews.mvp.model.helper;

import android.content.Context;

import javax.inject.Provider;

import dagger.internal.Factory;

public final class SPHelper_Factory implements Factory<SPHelper> {
  private final Provider<Context> contextProvider;

  public SPHelper_Factory(Provider<Context> contextProvider) {
    assert contextProvider != null;
    this.contextProvider = contextProvider;
  }

  @Override
  public SPHelper get() {
    return new SPHelper(contextProvider.get());
  }

  public static Factory<SPHelper> create(Provider<Context> contextProvider) {
    return new SPHelper_Factory(contextProvider);
  }
}
